## 1. Tutorial

### Biblioteka numpy

Numpy jest biblioteką do obliczeń numerycznych. Szczególnie dobrze nadaje się do operacji na macierzach
i wektorach.

Zwróć uwagę:

- numpy działa w oparciu nie o wbudowany typ <b>list</b>, ale o specjalny typ macierzowy <b>array</b>.
- <b>array</b> <a href="http://scipy-lectures.org/intro/numpy/array_object.html">umożliwia bardzo wygodne “krojenie” macierzy</a>

In [14]:
import numpy as np
from matplotlib import pyplot as plt
plt.rcParams['figure.figsize'] = [10, 10]

In [15]:
x = [1, 2, 3, 4, 5, 6]
v = np.array(x)
v

array([1, 2, 3, 4, 5, 6])

In [16]:
M = np.array([[1, 2], [3, 4]])
M

array([[1, 2],
       [3, 4]])

In [17]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [18]:
v.shape

(6,)

In [19]:
M.shape

(2, 2)

In [20]:
M.dtype

dtype('int32')

In [21]:
np.random.rand(5, 3)

array([[0.81419653, 0.97464408, 0.73145006],
       [0.91457168, 0.73710951, 0.74595578],
       [0.53100043, 0.56698434, 0.3048842 ],
       [0.48740088, 0.1492314 , 0.79522244],
       [0.47532864, 0.68587632, 0.30022851]])

In [22]:
M = np.array([[1, 2, 3], [4, 5, 6]])
N = np.array([[1, 1, 1], [2, 2, 2]])
print(N)
print(M)

[[1 1 1]
 [2 2 2]]
[[1 2 3]
 [4 5 6]]


In [23]:
M + N

array([[2, 3, 4],
       [6, 7, 8]])

In [24]:
5 * M

array([[ 5, 10, 15],
       [20, 25, 30]])

In [25]:
M * N

array([[ 1,  2,  3],
       [ 8, 10, 12]])

In [26]:
# Mnożenie macierzy
M.dot(N)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
# Transpozycja
M.dot(N.T)

In [ ]:
# Generowanie rownych odstepow
v = np.linspace(0, 10, 21)
v

In [ ]:
# Generowanie macierzy współrzędnych
x = np.linspace(0, 10, 21)
y = np.linspace(10, 20, 21)
xx, yy = np.meshgrid(x, y)
plt.scatter(xx, yy)

In [ ]:
np.sin(v)

In [ ]:
plt.plot(v, np.sin(v))
plt.show()

In [ ]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
M

In [ ]:
# Krojenie macierzy
# Wszystkie wiersze razy 2ga (trzecia) kolumna
M[:, 2]

In [ ]:
M[2, 1:3]

In [ ]:
M[1:3, 2:4]

In [ ]:
M[::2, :]

In [ ]:
M

In [ ]:
M[::2, ::2] = 0
M

### Kolory, obrazy

In [ ]:
def gen_img(n=9, start=-1.5, end=1.5, size=2000):
  # Inicjalizacja danych
  x = np.linspace(start, end, size)
  y = np.linspace(start, end, size)
  xx, yy = np.meshgrid(x, y)
  Z = xx + yy * 1j  # Tworzymy macierz wartości zespolonych

  for i in range(50):
    #Z =  ((n-1)/n)*Z + (1/n)*(1/(Z**(n-1))) # alternatywny obraz
    Z = ((n ** 2 - 12 / n ** 2) / n ** 2) * Z - 3 / n ** 2 + (1 / n ** 3) * (1 / (Z ** (n - 1)))

  # Argument liczby zespolonej
  img = np.angle(Z)
  # Normalizacja do zakresu 0-255
  return 255 * (img - np.min(img)) / np.ptp(img)

In [ ]:
# Można również przetestować funkcję dla innych n niż domyślne
img = gen_img()

In [ ]:
# Funkcja zwraca dwuwymiarową tablicę wartości z zakresu 0-255
print(img)

In [ ]:
# Wyświetlanie numpy array jako obrazu
plt.imshow(img)

In [ ]:
# Zmiana mapy kolorów
plt.imshow(img, cmap="terrain")

<a href="https://www.cs.put.poznan.pl/rsusmaga/Dydaktyka/TO--2017/TO-cz-1-wykladu-13-sent.pdf">Źródło</a> kodu generującego obraz wraz z objaśnieniem.

### Biblioteka skimage

In [ ]:
from skimage import io
from skimage import color

# Wczytywanie obrazu
img = io.imread('resources/lab-2/images/pic.jpg')

In [ ]:
# Obraz RGB
print(img[50:54, 50:54])

In [ ]:
plt.imshow(img)

In [ ]:
# Wczytywanie z konwersją RGB -> skala szarości
img_bw = io.imread('pic.jpg', as_gray=True)

In [ ]:
print(img_bw[50:54, 50:54])

In [ ]:
plt.imshow(img_bw)

In [ ]:
# Konwersja z RGB na skalę szarości
img_bw2 = color.rgb2gray(img)

### Dźwięk

In [ ]:
from playsound import playsound
from scipy.io import wavfile

In [ ]:
# Odtwarzanie dźwięku
playsound('resources/lab-2/sounds/err.wav')

In [ ]:
# Wczytywanie pliku wav
# samplerate to częstotliwość próbkowania, data to próbki
samplerate, data = wavfile.read('resources/lab-2/sounds/err.wav')

In [ ]:
# Zapisanie pliku wav
wavfile.write("resources/lab-2/sounds/test.wav", samplerate, data)

In [ ]:
# Sprawdzenie liczby próbek i liczby kanałów
np.shape(data)

## 2. Zadania

### Biblioteka numpy

1. Utwórz macierz 2D:

[ 1, 3, 1, 2]<br>
[ 1, 2, 5, 8]<br>
[ 3, 1, 2, 9]<br>
[ 5, 4, 2, 1]<br>

2. Wytnij z utworzonej macierzy pierwszy i ostatni wiersz oraz ostatnią kolumnę.

3. Utwórz macierz 2D:

[ 2, 3, 1]<br>
[ 5, 1, 3]<br>

4. Dokonaj transpozycji powyższej macierzy.

5. Oblicz iloczyn macierzy z punktu 2 i 4.

6. Stwórz wykres funkcji sin w przedziale od −π do π z liczbą punktów równą: 3, 10, 100.

### Obrazy

1. Przetestuj różne mapy kolorów korzystając z obrazu wygenerowanego przy użyciu funkcji gen_img()

2. Wczytaj obraz z pliku "pic.jpg" i sprawdź wymiary tablicy

3. Przekonwertuj obraz do skali szarości i sprawdź wymiary tablicy

4. Wyświetl obraz w skali szarości (poszukaj odpowiedniej mapy kolorów)

5. Wykadruj obraz tak aby na obrazie pozostała tylko głowa

6. Dokonaj inwersji kolorów (stwórz "negatyw" obrazu)

7. Korzystając z numpy wygeneruj poniższy obraz

![title](gradient.png)

8. Korzystając z numpy wygeneruj poniższy obraz

![title](goal.png)

### Dźwięki

1. Wczytaj pllik "err.wav"

2. Wyświetl wymiary tablicy przechowującej plik

3. Stwórz wykres przebiegu sygnału w czasie

4. Wczytaj plik "leto.wav"

5. Zastosuj efekt fade in (stopniowe zgłaśnianie) przemnażając próbki przez odpowiednie wagi i zapisując efekt do pliku .wav. Pamiętaj że nagranie ma dwie ścieżki.

6. Powtórz poprzednie polecenie, tym razem stosując fade-in logarytmiczny. Jaka jest różnica w porównaniu do poprzedniego podejścia? Dlaczego tak się dzieje? 

7. Odejmij od siebie wartości próbek w obu kanałach, podziel wynik przez dwa i zapisz do pliku .wav. Pamiętaj żeby przed zapisem do pliku przekonwertować wynik tej operacji na <b>int</b> korzystając z <b>astype('int16')</b>. Co się stało z nagraniem? Jaka jest tego przyczyna?